name: Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Rename config
      run: mv ./src/config.example.ts ./src/config.ts
    - name: Run tests
      run: yarn test
